use_recurrent_model_schedule: true
num_mem_tokens: 16
recurrent_chunk_size: 512
tensor_model_parallel_size: 1
pipeline_model_parallel_size: 1
seq_length: 2048
micro_batch_size: 1
global_batch_size: 8
position_embedding_type: rope
